spring:
  datasource:
    url: jdbc:h2:mem:db
    username: ajpv
    password:
    generate-unique-name: false
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
